### PR TITLE
this would be pretty cool if it was added

### PR DESCRIPTION
**Pull request by therandomspoon**
it adds like fps or summin idk

Me if they keeps this:
image

### CODE REVIEW

**Comment by IdotMaster1** [comment]
i am so fucking confused.
what.
- IdotMaster1

**Comment by GoldDominik893** [comment]
its literally so faster i tested

**Comment by therandomspoon** [comment]
coconut

**Comment by IdotMaster1** [comment]
average bunkercoin moment
literally

**Comment by therandomspoon** [comment]
pretty please 
image

**Comment by therandomspoon** [comment]
i made it 1.15.5-dev now. pretty please with gumdrops 
image

**Comment by therandomspoon** [comment]
im gonna stop protesting now this whole idea was stupid lol. but i am still going to make a brand around #coconutting

**Pull request closed without merging**
